### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by DeflatedPickle** [Sopiro/Java-OpenGL-Render-Engine#1]
I've been looking for a feature-rich renderer to use for one of my projects to quickly show models with some nice lighting and yours is quite complete! Great work with it! I was wondering if you'd consider adding a license (something compatible with MIT) so I could comfortably use it. Of course, your license would be included with my program, should you choose to add one and you'd be properly credited in the program once a credits window was added

I might also need to maintain a fork with some changes to integrate it with my project, though I'd be happy to work out a review stage and submit my changes as pull requests should they be of use to you

**Comment by Sopiro** [comment]
Hi. Sorry for late reply. I just added a license. This project is licensed under the MIT License! I hope the project goes well. Thank you.
